version: '3'
services:

  # 
  # VON Connector
  # 
  von_connector:
    build: .
    command: 'bash -c ''./scripts/start_von_connector.sh'''
    volumes:
      - ./connector:/mnt
    networks:
      - von
    external_links:
      - node1

networks:
  von:
