#!/bin/bash

set -e

SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"
export COMPOSE_PROJECT_NAME="von"

cd "$SCRIPT_HOME"

case "$1" in
  start)
      if [ -z "$2" ]; then
        docker-compose run von_connector
      else
        docker-compose run -e IP="$2" von_connector
      fi
    ;;
  bootstrap)
      if [ -z "$2" ]; then
        docker-compose run bootstrap
      else
        docker-compose run -e IP="$2" bootstrap
      fi
    ;;
  stop)
      docker-compose stop
    ;;
  build)
      docker-compose build
    ;;
  rebuild)
      docker-compose build --no-cache
    ;;
  *)
    echo $"Usage: $0 {start|stop|build|rebuild}"
esac

( cd - ) > /dev/null